swagger:
  enabled: true
db:
  type: 1
server:
  port: 80
spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    database1:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test_redis?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password:
    database2:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/test_redis?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=Asia/Shanghai
      username: root
      password:
    acquireIncrement: 5
    initialPoolSize: 5
    minPoolSize: 5
    maxPoolSize: 50
    maxWait: 60000
    maxPoolPreparedStatementPerConnectionSize: 100
    timeBetweenEvictionRunsMillis: 3000
    minEvictableIdleTimeMillis: 300000

thunisoft:
  hyyd:
    basic:
      server: ${random.uuid}
      url: http://172.16.6.211:10188
    zk:
      server: ${random.uuid}
      url: http://172.16.6.211:10199
gyp:
  server:
    feign:
        url: http://127.0.0.1:8080
